### ISSUE TITLE
"STEPNAME" are wrong when there are several scenarios in the same feature

### ISSUE THREAD

**Issue by dmtraining** [email2vimalraj/CucumberExtentReporter#2] opened 2016-04-08 17:45 UTC
Hello,

When I'm trying to run a feature file including several scenarios ("Scenario Outline" in my case), the "STEPNAME" column of the report file are wrong.

The steps names related to the 1st scenario are correct but not for the other ones.
In the section related to the 2nd scenario, I can see the steps name of the 1st scenation first and after, the ones related to the 2nd scenario.

**Example - Scenario 1 (3 steps)**
Given Scenario1_StepName_1
When Scenario1_StepName_2
Then  Scenario1_StepName_3

**Example - Scenario 2 (5 steps)**
Given Scenario2_StepName_1
When Scenario2_StepName_2
And Scenario2_StepName_3
Then  Scenario2_StepName_4
And  Scenario2_StepName_5

**The report file will be like that for the scenario 1**
<html>
<table>
<tr><td>STATUS</td><td>TIMESTAMP</td><td>STEPNAME</td><td>DETAILS</td></tr>
<tr><td>&nbsp;</td><td>&nbsp;</td><td>Scenario1_StepName_1</td><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td><td>&nbsp;</td><td>Scenario1_StepName_2</td><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td><td>&nbsp;</td><td>Scenario1_StepName_3</td><td>&nbsp;</td></tr>
</table>
</html>

**The report file will be like that for the scenario 2**
<html>
<table>
<tr><td>STATUS</td><td>TIMESTAMP</td><td>STEPNAME</td><td>DETAILS</td></tr>
<tr><td>&nbsp;</td><td>&nbsp;</td><td>Scenario1_StepName_1</td><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td><td>&nbsp;</td><td>Scenario1_StepName_2</td><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td><td>&nbsp;</td><td>Scenario1_StepName_3</td><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td><td>&nbsp;</td><td>Scenario2_StepName_1</td><td>&nbsp;</td></tr>
<tr><td>&nbsp;</td><td>&nbsp;</td><td>Scenario2_StepName_2</td><td>&nbsp;</td></tr>
</table>
</html>

Could you please help to fix this issue?

Thanks.

**Comment by dmtraining** [comment] 2016-04-12 08:31
Hi @email2vimalraj ,

Could you please help me?

Thanks.

**Comment by email2vimalraj** [comment] 2016-04-12 11:21
@dmtraining : I'll have a look and get back to you.

**Comment by email2vimalraj** [comment] 2016-04-17 09:14
@dmtraining : I confirm there is an issue. I'll work on fix and update you.

**Comment by dmtraining** [comment] 2016-04-17 11:37
Thanks @email2vimalraj. I'm waiting for your update :-)

**Comment by email2vimalraj** [comment] 2016-05-22 14:35
This issue is fixed now and will be part of the next release.

**Comment by email2vimalraj** [comment] 2016-05-23 02:19
@dmtraining : The issue has been fixed as part of the new release v1.1.0. Kindly update your pom and execute again.

Feel free to re-open in case the issue is not solved.

**Closed by email2vimalraj** 2016-05-23 02:19 UTC
Labels: bug
